---
kind: Template
apiVersion: v1
metadata:
  name: cakephp-multi-project-build
  annotations:
    openshift.io/display-name: CakePHP
    description: >-
      Build resource definitions for a CakePHP example configured across
      multiple namespaces. For more information about using this template,
      including OpenShift considerations, see
      https://github.com/redhat-gpte-devopsautomation/cakephp-ex/blob/master/README.md.
    tags: quickstart,php,cakephp
    iconClass: icon-php
    openshift.io/long-description: >-
      This template defines a BuildConfig and ImageStream for a CakePHP example
      application. This template is meant to be used with separate deployment
      and namespace initialization templates.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/documentation-url: https://github.com/redhat-gpte-devopsautomation/cakephp-ex
    template.openshift.io/bindable: 'false'
message: |-
  Build resources have been created in project: ${BUILD_NAMESPACE}.

  For more information about using this template, including OpenShift considerations, see https://github.com/redhat-gpte-devopsautomation/cakephp-ex/blob/master/README.md.
labels:
  template: cakephp-multi-project-build
  app: cakephp-example
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to the build objects defined in this template.
  required: true
  value: cakephp-example
- name: VERSION
  displayName: Version
  description: Build image output tag.
  required: true
  value: latest
- name: BUILD_NAMESPACE
  displayName: Build Namespace
  description: >-
    The OpenShift Namespace where the ImageStream and BuildConfig reside.
  required: true
  value: cakephp-example-build
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: The OpenShift Namespace where the PHP S2I ImageStream resides.
  required: true
  value: openshift
- name: PHP_VERSION
  displayName: PHP Version
  description: Version of PHP image to be used (7.1 or latest).
  required: true
  value: '7.3'
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your application source code.
  required: true
  value: https://github.com/redhat-gpte-devopsautomation/cakephp-ex.git
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
- name: CONTEXT_DIR
  displayName: Context Directory
  description: Set this to the relative path to your project if it is not in the root
    of your repository.
- name: GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: COMPOSER_MIRROR
  displayName: Custom Composer Mirror URL
  description: The custom Composer mirror URL
  value: ''
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${NAME}
    namespace: ${BUILD_NAMESPACE}
    annotations:
      description: Image stream for build output.
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
    namespace: ${BUILD_NAMESPACE}
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 512Mi
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${CONTEXT_DIR}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: ${IMAGE_NAMESPACE}
          name: php:${PHP_VERSION}
        env:
        - name: COMPOSER_MIRROR
          value: ${COMPOSER_MIRROR}
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${VERSION}
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_WEBHOOK_SECRET}
    postCommit:
      script: ./vendor/bin/phpunit
